# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActiveMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CorePlot', '~> 2.3'
  # Pods for ActiveMe

  target 'ActiveMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ActiveMeUITests' do
    # Pods for testing
  end

end
